# Generated by Django 6.0.8 on 2026-08-11 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a clear, descriptive title.', max_length=200)),
                ('content', models.TextField(help_text='Write your post content responsibly.')),
                ('category', models.CharField(choices=[('general', 'General Discussion'), ('cyber_safety', 'Cyber Safety & Advice'), ('experience', 'Personal Experience & Story'), ('question', 'Question / Support Request'), ('resource', 'Resource Sharing')], default='general', max_length=50)),
                ('is_flagged', models.BooleanField(default=False)),
                ('toxicity_label', models.CharField(default='Safe', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
